# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(dependabot):"
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: "quarterly"
    cooldown:
      default-days: 7
    groups:
      gha-updates:
        applies-to: version-updates
        patterns:
          - '*'
